### GENERAL SETTINGS ###

# Site settings
title: BristolJS
description: "We host monthly JavaScript meetings in the beautiful city of Bristol, UK."
analytics: UA-61237588-1
baseurl: ""
url: "http://bristoljs.lab.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: meetup
    url: http://meetup.com/BristolJS/
  - title: twitter
    url: http://twitter.com/bristoljs
